### PR TITLE
Scraper to csv

### PR DESCRIPTION
**Pull request by danielalfonsetti**

### CODE REVIEW

**Review by samimak37 — COMMENTED** [review]
This looks really good! It looks like you found some distinguishing tags that I couldn’t — Thank you!

Should we add the csv file to `.gitignore`? I feel like it’s not that important either way, but just to declutter the repo a little bit. 

Either way, thank you!

**Comment by danielalfonsetti** [comment]
I know that from a reproducibility standpoint keeping data on hand isn't great practice, but sometimes websites change their format, and then the scraper stops working correctly. I figure if we keep the csv file, it prevents us from having to make a new scraper on the off chance the site changes before the end of the term.

**Comment by danielalfonsetti** [comment]
I also restructured the directory just now.

**Review by samimak37 — COMMENTED** [review]
Awesome!!!! Thanks!!!! 

I changed `plots/README.md.py` and `misc/READ.md` to `README.md` files, but otherwise this seems great.

I just realized that you might not have merge access, so I'm going to try to fix that real quick. I can merge this right now if you're comfortable with it.

**Comment by danielalfonsetti** [comment]
Sure. And yea I have merge access, I just wanted to run it by you. Go ahead and merge it!

**Pull request merged**
